# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RpDhoZeU9Q4d31Lyx7OMk5cvfNwz7IHU
"""

num = int(input())
sum = 0
while num > 0:
  razr = num % 10
  sum += razr
  num //= 10
print(sum)