# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RpDhoZeU9Q4d31Lyx7OMk5cvfNwz7IHU
"""

n = int(input())
proizv = 1
for i in range(n, 1, -1):
  proizv *= i
print(proizv)