# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RpDhoZeU9Q4d31Lyx7OMk5cvfNwz7IHU
"""

n = int(input())
for i in range(1, n):
  if i % 7 == 0:
    print(i)